language: node_js
notifications:
  email: false
node_js:
  - '8'
  - '10'
install:
  - npm ci
script:
  - npm run build
  - npm run test
after_success:
  - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
